title: "Yang's AI Portfolio"
description: "人工智能 · 强化学习 · 项目展示 · 简历 · 博客"
baseurl: "" 
url: "https://hy888max.github.io"

remote_theme: "mmistakes/minimal-mistakes"

author:
  name: "Yang Hu"
  avatar: "/assets/images/avatar.png"
  bio: "AI student @ University of Alberta"
  location: "Canada"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
